version: '3'
services:
  mysql:
    image: 'mysql:8.0.19'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo_proto
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=root
      # - MYSQL_RANDOM_ROOT_PASSWORD="yes"
