// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package code

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *SendReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SendReq[number], err)
}

func (x *SendReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Phone, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SendReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Biz, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SendResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
}

func (x *VerifyReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_VerifyReq[number], err)
}

func (x *VerifyReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Phone, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *VerifyReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Biz, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *VerifyReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Code, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *VerifyResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
}

func (x *SendReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *SendReq) fastWriteField1(buf []byte) (offset int) {
	if x.Phone == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetPhone())
	return offset
}

func (x *SendReq) fastWriteField2(buf []byte) (offset int) {
	if x.Biz == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetBiz())
	return offset
}

func (x *SendResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	return offset
}

func (x *VerifyReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *VerifyReq) fastWriteField1(buf []byte) (offset int) {
	if x.Phone == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetPhone())
	return offset
}

func (x *VerifyReq) fastWriteField2(buf []byte) (offset int) {
	if x.Biz == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetBiz())
	return offset
}

func (x *VerifyReq) fastWriteField3(buf []byte) (offset int) {
	if x.Code == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetCode())
	return offset
}

func (x *VerifyResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	return offset
}

func (x *SendReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *SendReq) sizeField1() (n int) {
	if x.Phone == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetPhone())
	return n
}

func (x *SendReq) sizeField2() (n int) {
	if x.Biz == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetBiz())
	return n
}

func (x *SendResp) Size() (n int) {
	if x == nil {
		return n
	}
	return n
}

func (x *VerifyReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *VerifyReq) sizeField1() (n int) {
	if x.Phone == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetPhone())
	return n
}

func (x *VerifyReq) sizeField2() (n int) {
	if x.Biz == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetBiz())
	return n
}

func (x *VerifyReq) sizeField3() (n int) {
	if x.Code == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetCode())
	return n
}

func (x *VerifyResp) Size() (n int) {
	if x == nil {
		return n
	}
	return n
}

var fieldIDToName_SendReq = map[int32]string{
	1: "Phone",
	2: "Biz",
}

var fieldIDToName_SendResp = map[int32]string{}

var fieldIDToName_VerifyReq = map[int32]string{
	1: "Phone",
	2: "Biz",
	3: "Code",
}

var fieldIDToName_VerifyResp = map[int32]string{}
